# Generated by Django 5.1.2 on 2024-10-20 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_legal', models.CharField(max_length=255)),
                ('numero_registro', models.CharField(max_length=50)),
                ('tipo_empresa', models.CharField(max_length=100)),
                ('direccion_fiscal', models.CharField(max_length=255)),
                ('telefono_contacto', models.CharField(max_length=50)),
                ('correo_contacto', models.CharField(max_length=255)),
                ('pagina_web', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('tags', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(max_length=500)),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correo_electronico', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=50)),
                ('foto_perfil', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_identificacion', models.CharField(max_length=50)),
                ('tipo_rol', models.CharField(max_length=10)),
                ('ultima_conexion', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('notificaciones', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_match', models.DateTimeField()),
                ('etapa', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(max_length=500)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_1', to='restapp.usuario')),
                ('usuario_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_2', to='restapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(max_length=500)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.usuario')),
            ],
        ),
    ]
